neo4j_config:
  server: 0.0.0.0:7474
  username: neo4j
  password: root
  config_location: /home/tara/Documents/my/ai-code-scanner/my-test/neo4j/config
  data_location: /home/tara/Documents/my/ai-code-scanner/my-test/neo4j/data

nn_config:
  input_size: 100 # input_size x input_size
  label_class_size: 3
  iterations: 2000

joern_config:
  installed_location: /home/tara/Documents/my/ai-code-scanner/joern-0.3.1

trainer_config:
  apps_location: /home/tara/Documents/my/ai-code-scanner/my-test/ai-code-scanner-data/training-data

tester_config:
  apps_location: /home/tara/Documents/my/ai-code-scanner/my-test/ai-code-scanner-data/testing-data

predictor_config:
  app_location: /home/tara/Documents/my/ai-code-scanner/my-test/ai-code-scanner-data/testing-data/1/app-1
